import { Header } from '@/components';
import './global.css';
import { SolanaProvider, ClusterProvider, ReactQueryProvider } from '@/context';

export const metadata = {
  title: 'escrow',
  description: 'Generated by create-solana-dapp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <Header/>
              {children}
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
